Add Makefile target to run all benchmarks

diff --git a/sphincs256/ref/Makefile b/sphincs256/ref/Makefile
--- a/sphincs256/ref/Makefile
+++ b/sphincs256/ref/Makefile
@@ -71,5 +71,7 @@ test: ${TESTS}
 	done; true
 
 bench: ${BENCHS}
-	time -p sh -c "./bench_speed.o 1 10"
-	time -p sh -c "./bench_speed.o 2 10"
+	-@for bench in ${BENCHS}; do \
+		echo $${bench}; \
+		./$${bench} || echo "${BOLD}$${bench} ${RED}FAILED${NORMAL}"; \
+	done; true
