Fix tput error in Makefile for non-screen terminals
When running the `test` target in a terminal other than 'screen',
echoing the tput escape sequences seems to cause problems.
Wrapping them in quotes appears to fix that.

diff --git a/sphincs256/ref/Makefile b/sphincs256/ref/Makefile
--- a/sphincs256/ref/Makefile
+++ b/sphincs256/ref/Makefile
@@ -33,7 +33,7 @@ clean:
 
 test: ${TESTS}
 	-@for test in ${TESTS}; do \
-		echo $${test};\
-		./$${test} || echo ${BOLD}$${test} ${RED}FAILED${NORMAL};\
+		echo $${test}; \
+		./$${test} || echo "${BOLD}$${test} ${RED}FAILED${NORMAL}"; \
 	done; true
 
